;; ┌────────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▄█░█▀█░█▀▄░█░█░█░░░█▀▀░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░█░█░█░█░█░█░█░█░░░█▀▀░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀░▀░▀▀▀░▀▀░░▀▀▀░▀▀▀░▀▀▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/alsa]
type = internal/alsa
master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default
master-mixer = Master
interval = 5
format-volume = <ramp-volume> <label-volume>
format-muted = <label-muted>
format-muted-prefix = 
label-volume = %percentage%%
label-muted = " Muted"
label-muted-foreground = ${color.foreground-alt}
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-headphones-0 = 
; [module/backlight]
; type = internal/backlight
; card = amdgpu_bl0
; format = <ramp> <label>
; label = %percentage%%
; ramp-0 = 
; ramp-1 = 
; ramp-2 = 
; ramp-3 = 
; ramp-4 = 
[module/battery]
type = internal/battery
full-at = 99
battery = BAT1
adapter = ACAD
poll-interval = 2
time-format = %H:%M
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <label-full>
format-full-prefix = 
label-charging = %percentage%%
label-discharging = %percentage%%
label-full = " Full"
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 
animation-charging-0 = 
animation-charging-1 = 
animation-charging-framerate = 750
; [module/cpu]
; type = internal/cpu
; interval = 1
; format = <label>
; format-prefix = 
; label = " %percentage%%"
[module/date]
type = internal/date
interval = 1.0
time = " %I:%M %p"
time-alt = " %a, %d %b %Y"
format = <label>
label = %time%
; [module/filesystem]
; type = internal/fs
; mount-0 = /
; interval = 30
; fixed-values = true
; format-mounted = <label-mounted>
; format-mounted-prefix = 
; format-unmounted = <label-unmounted>
; format-unmounted-prefix = 
; label-mounted = " %free%"
; label-unmounted = " %mountpoint%: not mounted"
; [module/memory]
; type = internal/memory
; interval = 1
; format = <label>
; format-prefix = 
; label = " %mb_used%"
[module/mpd]
type = internal/mpd
interval = 1
format-online = <label-song> <icon-prev> <toggle> <icon-next>
format-online-prefix = 
format-offline = <label-offline>
format-offline-prefix = 
label-song =  " %artist% - %title%"
label-song-maxlen = 25
label-song-ellipsis = true
label-time = %elapsed% / %total%
label-offline = " Offline"
icon-play = 
icon-pause = 
icon-stop = 
icon-next = 
icon-prev = 
icon-seekf = 
icon-seekb = 
icon-random = 
icon-repeat = 
icon-repeatone = 
icon-single = 
icon-consume =
toggle-on-foreground = ${color.primary}
toggle-off-foreground = ${color.secondary}
[module/wired-network]
type = internal/network
interface = eth0
[module/wireless-network]
type = internal/network
interface = wlp3s0
[module/network]
type = internal/network
interface = wlan0
interval = 1.0
accumulate-stats = true
unknown-as-up = true
format-connected = <ramp-signal> <label-connected>
format-disconnected = <label-disconnected>
format-disconnected-prefix = 
label-connected = "%{A1:networkmanager_dmenu &:}%essid%%{A}"
label-disconnected = "%{A1:networkmanager_dmenu &:} Offline%{A}"
ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
[module/pulseaudio]
type = internal/pulseaudio
sink = alsa_output.pci-0000_03_00.6.analog-stereo


use-ui-max = false


interval = 5

format-volume = <ramp-volume> <label-volume>


format-muted = <label-muted>
format-muted-prefix = 

label-volume = %percentage%%

label-muted = " Muted"
label-muted-foreground = ${color.foreground-alt}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 


[module/temperature]
type = internal/temperature

interval = 0.5

thermal-zone = 0

hwmon-path = /sys/devices/pci0000:00/0000:00:01.3/0000:01:00.0/hwmon/hwmon0/temp1_input

warn-temperature = 65

units = true

format = <ramp> <label>

format-warn = <ramp> <label-warn>

label = %temperature-c%

label-warn = "%temperature-c%"
label-warn-foreground = ${color.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-5 = 


[module/keyboard]
type = internal/xkeyboard

blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-layout> <label-indicator>
format-prefix = 

label-layout = " %layout%"

label-indicator-on = %name%
label-indicator-on-foreground = ${color.primary}

[module/title]
type = internal/xwindow

format = <label>
format-prefix = 

label = " %title%"
label-maxlen = 30


[module/workspaces]
type = internal/xworkspaces

pin-workspaces = true

enable-click = true

enable-scroll = true
icon-0 = 1|
icon-1 = 2|
icon-2 = 3|
icon-3 = 4|
icon-4 = 5|
icon-default = 
format = <label-state>
format-padding = 0
label-monitor = %name%
label-active = %icon%
label-active-foreground = ${color.primary}
label-active-underline = ${color.primary}
label-occupied = %icon%
label-occupied-foreground = ${color.alternate}
label-urgent = %icon%
label-urgent-foreground = ${color.secondary}
label-empty = %icon%
label-active-padding = 2
label-urgent-padding = 2
label-occupied-padding = 2
label-empty-padding = 2