;; ┌────────────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀▀░█░█░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█▀▀░█▀▄░█▀▀░▀▄▀░░█░░█▀▀░█▄█░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀░░░▀░▀░▀▀▀░░▀░░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_


[global/wm]

margin-bottom = 0

margin-top = 0



include-file = ~/.config/polybar/material/bars.ini
include-file = ~/.config/polybar/material/colors.ini
include-file = ~/.config/polybar/material/modules.ini
include-file = ~/.config/polybar/material/user_modules.ini



[bar/main]
monitor =

monitor-fallback =
monitor-strict = false

override-redirect = false

bottom = true

fixed-center = true

width = 80%
height = 40


offset-x = 10%
offset-y = 2%

background = ${color.background}

foreground = ${color.foreground}

radius-top = 0.0
radius-bottom = 0.0

line-size = 2
line-color = ${color.primary}

border-size = 3
border-color = ${color.background}

padding = 0

module-margin-left = 2
module-margin-right = 2


font-0 = "Fantasque Sans Mono:pixelsize=12;3"
font-1 = "Material\-Design\-Iconic\-Font:size=13;4"

[bar/top]
inherit = bar/main
bottom = true
offset-y = 140
modules-left = launcher workspaces cpu memory
modules-center =  mpd
modules-right = alsa battery network date sysmenu
enable-ipc = true

[bar/mid]
inherit = bar/main
bottom = true
offset-y = 80
modules-center = volume brightness battery_bar mpd_bar cpu_bar filesystem_bar memory_bar
enable-ipc = true

[bar/bottom]
inherit = bar/main
bottom = true
modules-left = menu term files browser settings filesystem temperature
modules-center =  title
modules-right = color-switch keyboard pulseaudio backlight updates powermenu
enable-ipc = true


separator = 

dim-value = 1.0


wm-name = 
locale = 
tray-position = none

tray-detached = false

tray-maxsize = 16
tray-background = ${color.background}

tray-offset-x = 0
tray-offset-y = 0

tray-padding = 0

tray-scale = 1.0
click-left = 
click-middle = 
click-right =
scroll-up =
scroll-down =
double-click-left =
double-click-middle =
double-click-right =
cursor-click = 
cursor-scroll = 


[settings]
throttle-output = 5
throttle-output-for = 10

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false

